name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      # Caching yarn dependencies
      - name: Cache yarn dependencies
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install package dependencies
        run: yarn install

      - name: Check linting and formatting
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Create test build
        run: yarn build
